---
galaxy_info:
  role_name: oracle_install
  author: Naved Afroz
  description: This role to Upgrade Oracle Database from 12c to 19c using autoupgrade utility. 
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
