---
galaxy_info:
  role_name: dataguard_create_standby
  author: Naved Afroz
  description: Ansible role creates standby database .
  company: IBM

  license: Apache-2.0

  min_ansible_version: '2.9'

  platforms:
    - name: AIX
      versions:
        - all

  galaxy_tags: [aix]
dependencies: []
